/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Content;

import Models.Conta;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import Models.OrdemServico;
import Models.Registro;
import Models.Veterinario;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author thayn
 */
public class VisualizarOrdemServico extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisualizarOrdemServico
     */
    private Veterinario vet;
    private Registro reg;
    private ArrayList<OrdemServico> ordens = new ArrayList<>();
    private static VisualizarOrdemServico tela;

    public VisualizarOrdemServico() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    public VisualizarOrdemServico(Veterinario vet, Registro reg) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        this.vet = vet;
        this.reg = reg;
    }

    public ArrayList<OrdemServico> getOrdens() {
        return ordens;
    }

    public void setOrdens(ArrayList<OrdemServico> ordens) {
        this.ordens = ordens;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        pnl_principal = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_titulo = new javax.swing.JLabel();
        lbl_comboBox = new javax.swing.JLabel();
        pnl_cliente = new javax.swing.JPanel();
        lbl_dados_cliente = new javax.swing.JLabel();
        lbl_id_cliente = new javax.swing.JLabel();
        lbl_nome_cliente = new javax.swing.JLabel();
        lbl_endereco_cliente = new javax.swing.JLabel();
        txt_id_cliente = new javax.swing.JTextField();
        txt_nome_cliente = new javax.swing.JTextField();
        txt_endereco_cliente = new javax.swing.JTextField();
        pnl_servico = new javax.swing.JPanel();
        lbl_subTitulo_Servico = new javax.swing.JLabel();
        lbl_id_servico = new javax.swing.JLabel();
        lbl_nome_servico = new javax.swing.JLabel();
        lbl_valor_servico = new javax.swing.JLabel();
        lbl_animal_servico = new javax.swing.JLabel();
        lbl_relatorio_servico = new javax.swing.JLabel();
        lbl_data_servico = new javax.swing.JLabel();
        btn_salvar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        txt_nome_servico = new javax.swing.JTextField();
        txt_id_servico = new javax.swing.JTextField();
        txt_animal_servico = new javax.swing.JTextField();
        txt_valor_servico = new javax.swing.JTextField();
        txt_data_servico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_relatorio_servico = new javax.swing.JTextArea();
        cmb_OrdemServico = new javax.swing.JComboBox<>();
        lbl_subtitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        pnl_principal.setBackground(new java.awt.Color(238, 238, 238));

        lbl_titulo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(13, 36, 51));
        lbl_titulo.setText("Gerar Relatório da Ordem de Serviço");

        lbl_comboBox.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lbl_comboBox.setForeground(new java.awt.Color(16, 16, 16));
        lbl_comboBox.setText("Ordem de serviço:");

        lbl_dados_cliente.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lbl_dados_cliente.setText("Dados do Cliente");
        lbl_dados_cliente.setMaximumSize(new java.awt.Dimension(106, 15));
        lbl_dados_cliente.setMinimumSize(new java.awt.Dimension(106, 15));

        lbl_id_cliente.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbl_id_cliente.setText("ID:");

        lbl_nome_cliente.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbl_nome_cliente.setText("Nome:");

        lbl_endereco_cliente.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbl_endereco_cliente.setText("Endereço:");

        txt_id_cliente.setEnabled(false);
        txt_id_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_clienteActionPerformed(evt);
            }
        });

        txt_nome_cliente.setEnabled(false);
        txt_nome_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nome_clienteActionPerformed(evt);
            }
        });

        txt_endereco_cliente.setEnabled(false);

        javax.swing.GroupLayout pnl_clienteLayout = new javax.swing.GroupLayout(pnl_cliente);
        pnl_cliente.setLayout(pnl_clienteLayout);
        pnl_clienteLayout.setHorizontalGroup(
            pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_clienteLayout.createSequentialGroup()
                .addGroup(pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_clienteLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_nome_cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(lbl_id_cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_endereco_cliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_endereco_cliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_id_cliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nome_cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)))
                    .addGroup(pnl_clienteLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lbl_dados_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnl_clienteLayout.setVerticalGroup(
            pnl_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_clienteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_dados_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_id_cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(lbl_nome_cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_endereco_cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_endereco_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        lbl_subTitulo_Servico.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lbl_subTitulo_Servico.setText("Dados do Serviço");

        lbl_id_servico.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbl_id_servico.setText("ID:");

        lbl_nome_servico.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbl_nome_servico.setText("Nome:");

        lbl_valor_servico.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbl_valor_servico.setText("Valor:");

        lbl_animal_servico.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbl_animal_servico.setText("Animal:");

        lbl_relatorio_servico.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbl_relatorio_servico.setText("Relatório:");

        lbl_data_servico.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbl_data_servico.setText("Data:");

        btn_salvar.setText("Salvar");
        btn_salvar.setEnabled(false);
        btn_salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salvarMouseClicked(evt);
            }
        });
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        txt_nome_servico.setEnabled(false);
        txt_nome_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nome_servicoActionPerformed(evt);
            }
        });

        txt_id_servico.setEnabled(false);
        txt_id_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_servicoActionPerformed(evt);
            }
        });

        txt_animal_servico.setEnabled(false);

        txt_valor_servico.setEnabled(false);

        txt_relatorio_servico.setColumns(20);
        txt_relatorio_servico.setRows(5);
        jScrollPane1.setViewportView(txt_relatorio_servico);

        javax.swing.GroupLayout pnl_servicoLayout = new javax.swing.GroupLayout(pnl_servico);
        pnl_servico.setLayout(pnl_servicoLayout);
        pnl_servicoLayout.setHorizontalGroup(
            pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_servicoLayout.createSequentialGroup()
                .addGroup(pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_servicoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_relatorio_servico)
                            .addGroup(pnl_servicoLayout.createSequentialGroup()
                                .addGroup(pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_animal_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_servicoLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_animal_servico)
                                            .addGroup(pnl_servicoLayout.createSequentialGroup()
                                                .addGroup(pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_id_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbl_id_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl_nome_servico)
                                                    .addComponent(txt_nome_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(23, 23, 23)
                                .addGroup(pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_valor_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_valor_servico)))
                            .addGroup(pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnl_servicoLayout.createSequentialGroup()
                                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl_servicoLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_data_servico)
                            .addComponent(txt_data_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_servicoLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(lbl_subTitulo_Servico)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnl_servicoLayout.setVerticalGroup(
            pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_servicoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lbl_subTitulo_Servico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nome_servico)
                    .addComponent(lbl_valor_servico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nome_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_valor_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_data_servico)
                    .addComponent(lbl_animal_servico))
                .addGap(3, 3, 3)
                .addGroup(pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_data_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_animal_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_relatorio_servico)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(pnl_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        cmb_OrdemServico.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmb_OrdemServicoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cmb_OrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_OrdemServicoActionPerformed(evt);
            }
        });

        lbl_subtitulo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lbl_subtitulo.setForeground(new java.awt.Color(41, 52, 55));
        lbl_subtitulo.setText("Gere relatório das consultas através do formulário abaixo.");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel1.setText("*Selecione a ordem de serviço desejada para visualizar os dados");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N

        javax.swing.GroupLayout pnl_principalLayout = new javax.swing.GroupLayout(pnl_principal);
        pnl_principal.setLayout(pnl_principalLayout);
        pnl_principalLayout.setHorizontalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pnl_principalLayout.createSequentialGroup()
                .addComponent(pnl_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_servico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_principalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_principalLayout.createSequentialGroup()
                        .addComponent(lbl_titulo)
                        .addGap(234, 234, 234))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_principalLayout.createSequentialGroup()
                        .addComponent(lbl_subtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_principalLayout.createSequentialGroup()
                        .addComponent(lbl_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cmb_OrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143))))
        );
        pnl_principalLayout.setVerticalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_principalLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_subtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_principalLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2)
                        .addGap(362, 362, 362))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_principalLayout.createSequentialGroup()
                        .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_OrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl_servico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 826, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        txt_relatorio_servicoActionPerformed(evt);
    }

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void txt_id_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_clienteActionPerformed

    private void txt_nome_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nome_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nome_clienteActionPerformed

    private void txt_nome_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nome_servicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nome_servicoActionPerformed

    private void txt_id_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_servicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_servicoActionPerformed

    private void cmb_OrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_OrdemServicoActionPerformed
        if (!ordens.isEmpty())
            mostrarDados();
    }//GEN-LAST:event_cmb_OrdemServicoActionPerformed

    private void btn_salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salvarMouseClicked
        if (!ordens.isEmpty()) { //verifica se há ordem de serviço no combobox
            String relatorio = txt_relatorio_servico.getText(); //pega o relatorio digitado na tela
            if (relatorio.isEmpty()) { //verifica se o relatorio digitado não está vazio
                JOptionPane.showMessageDialog(null, "Favor escrever o relatório!");
            } else {
                OrdemServico ordemaux = getOrdens().get(cmb_OrdemServico.getSelectedIndex()); 
                if (relatorio.equals(ordemaux.getRelatorio())) { //verifica se a o relatorio digitado é igual ao que já se encontra na ordem
                    JOptionPane.showMessageDialog(null, "Relatório informado é igual ao cadastrado!");
                } else {
                    vet.cadastrarRelatorioOrdem(ordemaux, relatorio);//salva o relatorio na ordem selecionada no combobox
                    JOptionPane.showMessageDialog(null, "Relatório Salvo!");
                }
            }
        }

    }//GEN-LAST:event_btn_salvarMouseClicked

    private void cmb_OrdemServicoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmb_OrdemServicoAncestorAdded

        if (!ordens.isEmpty()) //verifica se há ordem de serviço no combobox para mostrar os dados na tela
            mostrarDados();
    }//GEN-LAST:event_cmb_OrdemServicoAncestorAdded

    public void mostrarDados() { //Função responsável por setar os campos e botões da tela

        OrdemServico ordemAux = ordens.get(cmb_OrdemServico.getSelectedIndex());

        if (ordemAux.getCliente() != null) { //tratamento para quando há clientes e para quando não há cliente cadastrado na ordem
            txt_id_cliente.setText(String.valueOf(ordemAux.getCliente().getId()));
            txt_id_cliente.setEnabled(true);
            txt_id_cliente.setEditable(false);
            txt_nome_cliente.setText(ordemAux.getCliente().getNome());
            txt_nome_cliente.setEnabled(true);
            txt_nome_cliente.setEditable(false);
            txt_endereco_cliente.setText(ordemAux.getCliente().getEndereco());
            txt_endereco_cliente.setEnabled(true);
            txt_endereco_cliente.setEditable(false);
        } else {
            txt_id_cliente.setText("---");
            txt_id_cliente.setEnabled(true);
            txt_id_cliente.setEditable(false);
            txt_nome_cliente.setText(ordemAux.getNomeCliente());
            txt_nome_cliente.setEnabled(true);
            txt_nome_cliente.setEditable(false);
            txt_endereco_cliente.setText("---");
            txt_endereco_cliente.setEnabled(true);
            txt_endereco_cliente.setEditable(false);
        }

        txt_id_servico.setText(String.valueOf(ordemAux.getServico().getId()));
        txt_id_servico.setEnabled(true);
        txt_id_servico.setEditable(false);
        txt_nome_servico.setText(ordemAux.getServico().getNome());
        txt_nome_servico.setEnabled(true);
        txt_nome_servico.setEditable(false);
        txt_animal_servico.setText(ordemAux.getAnimal());
        txt_animal_servico.setEnabled(true);
        txt_animal_servico.setEditable(false);

        txt_data_servico.setText(ordemAux.getDatatime().toString());
        txt_data_servico.setEnabled(true);
        txt_data_servico.setEditable(false);

        txt_valor_servico.setText(String.valueOf(ordemAux.getServico().getValor()));
        txt_valor_servico.setEnabled(true);
        txt_valor_servico.setEditable(false);

        txt_relatorio_servico.setText(ordemAux.getRelatorio());

        btn_cancelar.setEnabled(true);
        btn_cancelar.setVisible(true);
    }

    public void visualizarOrdem() {
        //Atualiza os titulos da janela
        lbl_titulo.setText("Ordem de Serviço");
        lbl_subtitulo.setText("Visualize as ordens de serviço através do formulário abaixo.");

        //Atualizando o comboBox
        cmb_OrdemServico.removeAllItems(); //Remove os itens existentes na lista

        if (!reg.getOrdemServicos().isEmpty()) { // verifica se há ordens de serviço
            reg.getOrdemServicos().forEach(ordem -> {
                if (ordem.getCliente() != null) { // Verifica se a ordem possui ou não cliente cadastrado para preencher corretamente os campos do cliente
                    cmb_OrdemServico.addItem("ID:" + ordem.getId() + " | Cliente: " + ordem.getCliente().getNome());
                    getOrdens().add(ordem);
                } else {
                    cmb_OrdemServico.addItem("ID:" + ordem.getId() + " | Cliente: " + ordem.getNomeCliente());
                    getOrdens().add(ordem);
                }
            });
        }

        //seta alguns campos da janela
        txt_relatorio_servico.setEnabled(false);
        txt_relatorio_servico.setEditable(false);
        btn_salvar.setEnabled(false);
        btn_salvar.setVisible(false);
        btn_cancelar.setText("Voltar");
    }

    public void GerarRelatorio_OrdemServico() {
        //Atualiza os titulos da janela
        lbl_titulo.setText("Gerar Relatório da Ordem de Serviço");
        lbl_subtitulo.setText("Gere relatório das consultas através do formulário abaixo.");

        //Atualizando o comboBox
        cmb_OrdemServico.removeAllItems();

        getOrdens().removeAll(reg.getOrdemServicos());
        if (!reg.getOrdemServicos().isEmpty()) { // verifica se há ordens de serviço
            reg.getOrdemServicos().forEach(ordem -> {
                if (ordem.getServico().getNome().equals("Consulta")) { //Verifica se a ordem é do tipo Consulta, pois é a única que o veterinario pode
                    //adicionar relatório
                    if (ordem.getCliente() != null) {// Verifica se a ordem possui ou não cliente cadastrado para preencher corretamente os campos do cliente
                        cmb_OrdemServico.addItem("ID:" + ordem.getId() + " | Cliente: " + ordem.getCliente().getNome());
                        getOrdens().add(ordem);
                    } else {
                        cmb_OrdemServico.addItem("ID:" + ordem.getId() + " | Cliente: " + ordem.getNomeCliente());
                        getOrdens().add(ordem);
                    }
                }

            });
        }
        //seta alguns campos da janela

        txt_relatorio_servico.setEnabled(true);
        txt_relatorio_servico.setEditable(true);
        btn_salvar.setEnabled(true);
        btn_salvar.setVisible(true);
        btn_cancelar.setText("Cancelar");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<String> cmb_OrdemServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lbl_animal_servico;
    private javax.swing.JLabel lbl_comboBox;
    private javax.swing.JLabel lbl_dados_cliente;
    private javax.swing.JLabel lbl_data_servico;
    private javax.swing.JLabel lbl_endereco_cliente;
    private javax.swing.JLabel lbl_id_cliente;
    private javax.swing.JLabel lbl_id_servico;
    private javax.swing.JLabel lbl_nome_cliente;
    private javax.swing.JLabel lbl_nome_servico;
    private javax.swing.JLabel lbl_relatorio_servico;
    private javax.swing.JLabel lbl_subTitulo_Servico;
    private javax.swing.JLabel lbl_subtitulo;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_valor_servico;
    private javax.swing.JPanel pnl_cliente;
    private javax.swing.JPanel pnl_principal;
    private javax.swing.JPanel pnl_servico;
    private javax.swing.JTextField txt_animal_servico;
    private javax.swing.JTextField txt_data_servico;
    private javax.swing.JTextField txt_endereco_cliente;
    private javax.swing.JTextField txt_id_cliente;
    private javax.swing.JTextField txt_id_servico;
    private javax.swing.JTextField txt_nome_cliente;
    private javax.swing.JTextField txt_nome_servico;
    private javax.swing.JTextArea txt_relatorio_servico;
    private javax.swing.JTextField txt_valor_servico;
    // End of variables declaration//GEN-END:variables

    private void txt_relatorio_servicoActionPerformed(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
